In [1]:
import torch

In [2]:
from torch.utils.data import DataLoader

t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)
for elem in data_loader:
    print(elem)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [3]:
t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t, batch_size=3, drop_last=False)
for i, batch in enumerate(data_loader):
    print(f'Batch #{i+1}: {batch}')

Batch #1: tensor([0., 1., 2.])
Batch #2: tensor([3., 4., 5.])


In [4]:
x = torch.rand([4, 3])
y = torch.arange(4)

In [5]:
from torch.utils.data import Dataset

class JointDataset(Dataset):

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]

In [6]:
from torch.utils.data import TensorDataset

joint_dataset = TensorDataset(x, y)
joint_2 = JointDataset(x, y)

In [7]:
for example in joint_dataset:
    print(example)
print('---------------------------------------------')
for example in joint_2:
    print(example)

(tensor([0.3583, 0.4001, 0.7345]), tensor(0))
(tensor([0.4698, 0.1522, 0.3029]), tensor(1))
(tensor([0.2957, 0.9358, 0.9266]), tensor(2))
(tensor([0.5378, 0.7651, 0.7834]), tensor(3))
---------------------------------------------
(tensor([0.3583, 0.4001, 0.7345]), tensor(0))
(tensor([0.4698, 0.1522, 0.3029]), tensor(1))
(tensor([0.2957, 0.9358, 0.9266]), tensor(2))
(tensor([0.5378, 0.7651, 0.7834]), tensor(3))
