In [1]:
import torch

In [2]:
torch.empty(3, 3, 3)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [3]:
torch.rand(2, 2)

tensor([[0.5004, 0.3650],
        [0.4948, 0.5543]])

In [4]:
torch.ones(2, 2, dtype=int)

tensor([[1, 1],
        [1, 1]])

In [5]:
x = torch.zeros(2, 2)
x[0, 0].dtype

torch.float32

In [6]:
x, y = torch.rand(2, 2), torch.rand(2, 2)
z = x + y
x, y, z == torch.add(x, y)

(tensor([[0.1407, 0.9019],
         [0.3224, 0.5378]]),
 tensor([[0.1900, 0.1071],
         [0.6439, 0.0356]]),
 tensor([[True, True],
         [True, True]]))

In [7]:
x = torch.rand(5, 3)

In [8]:
x.view(-1)

tensor([0.7816, 0.7064, 0.3032, 0.6082, 0.1562, 0.7432, 0.1112, 0.9439, 0.2625,
        0.9974, 0.0454, 0.9126, 0.8246, 0.1925, 0.8662])

In [9]:
x.view(-1, 3)

tensor([[0.7816, 0.7064, 0.3032],
        [0.6082, 0.1562, 0.7432],
        [0.1112, 0.9439, 0.2625],
        [0.9974, 0.0454, 0.9126],
        [0.8246, 0.1925, 0.8662]])

In [10]:
import numpy as np

In [11]:
y = x.numpy()
type(x), type(y)

(torch.Tensor, numpy.ndarray)

In [12]:
x, x * 2

(tensor([[0.7816, 0.7064, 0.3032],
         [0.6082, 0.1562, 0.7432],
         [0.1112, 0.9439, 0.2625],
         [0.9974, 0.0454, 0.9126],
         [0.8246, 0.1925, 0.8662]]),
 tensor([[1.5633, 1.4127, 0.6064],
         [1.2164, 0.3124, 1.4864],
         [0.2225, 1.8877, 0.5249],
         [1.9948, 0.0908, 1.8252],
         [1.6491, 0.3849, 1.7325]]))

In [15]:
x

tensor([[4.7816, 4.7064, 4.3032],
        [4.6082, 4.1562, 4.7432],
        [4.1112, 4.9439, 4.2625],
        [4.9974, 4.0454, 4.9126],
        [4.8246, 4.1925, 4.8662]])

In [16]:
x.add_(2)

tensor([[6.7816, 6.7064, 6.3032],
        [6.6082, 6.1562, 6.7432],
        [6.1112, 6.9439, 6.2625],
        [6.9974, 6.0454, 6.9126],
        [6.8246, 6.1925, 6.8662]])

In [18]:
x.add(2), x

(tensor([[8.7816, 8.7064, 8.3032],
         [8.6082, 8.1562, 8.7432],
         [8.1112, 8.9439, 8.2625],
         [8.9974, 8.0454, 8.9126],
         [8.8246, 8.1925, 8.8662]]),
 tensor([[6.7816, 6.7064, 6.3032],
         [6.6082, 6.1562, 6.7432],
         [6.1112, 6.9439, 6.2625],
         [6.9974, 6.0454, 6.9126],
         [6.8246, 6.1925, 6.8662]]))

In [ ]:
torch.cuda.is_available()

False