In [1]:
import torch

In [3]:
from torch.utils.data import DataLoader

t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t)
for elem in data_loader:
    print(elem)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [7]:
t = torch.arange(6, dtype=torch.float32)
data_loader = DataLoader(t, batch_size=3, drop_last=False)
for i, batch in enumerate(data_loader):
    print(f'Batch #{i+1}: {batch}')

Batch #1: tensor([0., 1., 2.])
Batch #2: tensor([3., 4., 5.])


In [8]:
x = torch.rand([4, 3])
y = torch.arange(4)

In [9]:
from torch.utils.data import Dataset

class JointDataset(Dataset):

    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, index):
        return self.x[index], self.y[index]

In [18]:
from torch.utils.data import TensorDataset

joint_dataset = TensorDataset(x, y)
joint_2 = JointDataset(x, y)

In [23]:
for example in joint_dataset:
    print(example)
print('---------------------------------------------')
for example in joint_2:
    print(example)

(tensor([0.8757, 0.5015, 0.0123]), tensor(0))
(tensor([0.1130, 0.1467, 0.5133]), tensor(1))
(tensor([0.4875, 0.1534, 0.1759]), tensor(2))
(tensor([0.8649, 0.9311, 0.1141]), tensor(3))
---------------------------------------------
(tensor([0.8757, 0.5015, 0.0123]), tensor(0))
(tensor([0.1130, 0.1467, 0.5133]), tensor(1))
(tensor([0.4875, 0.1534, 0.1759]), tensor(2))
(tensor([0.8649, 0.9311, 0.1141]), tensor(3))
